### ISSUE TITLE
Explorer is not reflecting the time range

### ISSUE THREAD

**Issue by martapiekarska** [davidgasquez/filecoin-data-portal#30]
In the view https://filecoinpulse.pages.dev/allocators/, the time range selector does not impact the adjustment of allocator explorer view. Crucially, the allocator explorer shows both active and inactive allocators (where inactive are basically those who used to be notaries). This results in the explorer not being very useful for finding potential allocators. Also, moving forward - when allocators get slashed for bad behaviour, they should be distinguishable from the active ones

**Comment by davidgasquez** [comment]
Hey @martapiekarska! 

> the time range selector does not impact the adjustment of allocator explorer view

Great catch! Should be fixed in the next deployment. :blush: 

> he allocator explorer shows both active and inactive allocators (where inactive are basically those who used to be notaries)

These are the allocators that are being shown. Which should be the ones returned in this API call: `http://api.datacapstats.io/api/getVerifiers?showInactive=false`.

![screenshot-2024-04-24_12:21:58](https://github.com/davidgasquez/filecoin-data-portal/assets/1682202/ea6bd5dd-f067-4ebb-afa4-1fd07bba2562)

The way I'm defining active allocators is by looking at their `created_height`.

https://github.com/davidgasquez/filecoin-data-portal/blob/f05d32e369a47ce288a45c240d4200b656ea23d4/dbt/models/filecoin_allocators.sql#L20

Is that assumption correct?

> When allocators get slashed for bad behaviour, they should be distinguishable from the active ones

Is there a field or a way for me to know if the allocators are slashed?

**Comment by davidgasquez** [comment]
The [Allocators explorer](https://filecoinpulse.pages.dev/allocators/) should now be filtered by the date range!
